/*
 * SPDX-FileCopyrightText: 2026 f3rhd 
 *
 * SPDX-License-Identifier: MIT
 */

#pragma once
#include <Visualizer/Camera.h>
namespace OoOVisual
{
	namespace Visualizer
	{
		enum class DRAW_ELEMENT_ID {
			FETCH_UNIT
			, FETCH_GROUP
			, DISPATCHER
			, STATION_0
			, STATION_1
			, STATION_2
			, STATION_3
			, STATION_4
			, STATION_5
			, STATION_6
			, ADDER_SUBTRACTOR_UNIT
			, BITWISE_UNIT
			, LESS_THAN_SETTER_UNIT
			, MULTIPLIER_UNIT
			, DIVIDER_UNIT
			, LOAD_STORE_UNIT
			, BRANCH_UNIT
			, REGISTER_MANAGER
			, REORDER_BUFFER
			, WIRE_FETCHGROUP_TO_DISPATCHER
			, WIRE_FETCH_TO_FETCHGROUP
			, WIRE_DISPATCHER_FANOUT_VERTICAL
			, WIRE_DISPATCHER_FANOUT_HORIZONTAL
			, WIRE_DISPATCHER_TO_STATION_0
			, WIRE_DISPATCHER_TO_STATION_1
			, WIRE_DISPATCHER_TO_STATION_2
			, WIRE_DISPATCHER_TO_STATION_3
			, WIRE_DISPATCHER_TO_STATION_4
			, WIRE_DISPATCHER_TO_STATION_5
			, WIRE_DISPATCHER_TO_STATION_6
			, WIRE_STATION_0_TO_ADDER
			, WIRE_STATION_1_TO_BITWISE
			, WIRE_STATION_2_TO_LESSTHAN
			, WIRE_STATION_3_TO_MULTIPLIER
			, WIRE_STATION_4_TO_DIVIDER
			, WIRE_STATION_5_TO_LOADSTORE
			, WIRE_STATION_6_TO_BRANCH

			, WIRE_ADDER_TO_ROB
			, WIRE_BITWISE_TO_ROB
			, WIRE_LESSTHAN_TO_ROB
			, WIRE_MULTIPLIER_TO_ROB
			, WIRE_DIVIDER_TO_ROB
			, WIRE_LOADSTORE_TO_ROB
			, WIRE_BRANCH_TO_ROB


			, WIRE_ROB_TO_REGFILE_HORIZONTAL
			, WIRE_ROB_TO_REGFILE_VERTICAL
			, WIRE_ROB_TO_REGFILE_TO_SIDE

			, SCREEN
			//,WIRE_REGFILE_TO_DISPATCHER_HORIZONTAL
			//,WIRE_REGFILE_TO_DISPATCHER_VERTICAL
			//,WIRE_REGFILE_TO_DISPATCHER_TO_RIGHT

		};
		struct Draw_Element

		{
			virtual ~Draw_Element() = default;
			virtual void draw(const Camera& cam) = 0;
			Draw_Element(DRAW_ELEMENT_ID id) : _id(id) {}
			DRAW_ELEMENT_ID id() const { return _id; }
		protected:
			DRAW_ELEMENT_ID _id;
		};
	}
}