/*
 * SPDX-FileCopyrightText: 2026 f3rhd 
 *
 * SPDX-License-Identifier: MIT
 */

#pragma  once
namespace OoOVisual
{
	namespace Core
	{
		enum class EXECUTION_UNIT_MODE : unsigned int {
			BRANCH_UNCONDITIONAL_JAL,
			BRANCH_UNCONDITIONAL_JALR,
			BRANCH_CONDITIONAL_GREATER_OR_EQUAL_THAN_UNSIGNED,
			BRANCH_CONDITIONAL_GREATER_OR_EQUAL_THAN,
			BRANCH_CONDITIONAL_EQUAL,
			BRANCH_CONDITIONAL_NOT_EQUAL,
			BRANCH_CONDITIONAL_LESS_THAN,
			BRANCH_CONDITIONAL_GREATER_THAN,
			BRANCH_CONDITIONAL_LESS_THAN_UNSIGNED,
			BRANCH_CONDITIONAL_GREATER_THAN_UNSIGNED,
			LOAD_STORE_LOAD_WORD,
			LOAD_STORE_LOAD_BYTE,
			LOAD_STORE_LOAD_HALF,
			LOAD_STORE_LOAD_BYTE_UNSIGNED,
			LOAD_STORE_LOAD_HALF_UNSIGNED,
			LOAD_STORE_STORE_WORD,
			LOAD_STORE_STORE_BYTE,
			LOAD_STORE_STORE_HALF,
			ADD_SUB_UNIT_ADD,
			ADD_SUB_UNIT_SUB,
			ADD_SUB_UNIT_LOAD_UPPER,
			ADD_SUB_UNIT_AUIPC,
			DIVIDER_DIVIDE_SIGNED,
			DIVIDER_DIVIDE_UNSIGNED,
			DIVIDER_REMAINDER_SIGNED,
			DIVIDER_REMAINDER_UNSIGNED,
			MULTIPLIER_MULTIPLY_SIGNED,
			MULTIPLIER_MULTIPLY_HIGH,
			MULTIPLIER_MULTIPLY_HIGH_SIGNED_UNSIGNED,
			MULTIPLIER_MULTIPLY_HIGH_UNSIGNED,
			BITWISE_AND,
			BITWISE_XOR,
			LOGICAL_XOR,
			BITWISE_SHIFT_LEFT_LOGICAL,
			BITWISE_SHIFT_RIGHT_LOGICAL,
			BITWISE_SHIFT_RIGHT_ARITHMETIC,
			SET_LESS_THAN,
			UNKNOWN
		};
	}
}